### ISSUE TITLE
NoMethodError on nfs_client recipe

### ISSUE THREAD

**Issue by marcy-terui** [megumiteam/chef-amimoto#23]
こんにちは！

JAWS-UG札幌の照井です。

`JIN-KEI 長篠`のVPC対応をしてみましたが、以下のエラーでNFSマウントに失敗していました。
原因切り分けはまだできていませんが、とりあえずご報告まで。

テンプレートは以下にあります。
https://github.com/marcy-terui/jinkei-nagashino-vpc

```
Generated at 2015-03-12 18:15:28 +0800
NoMethodError: undefined method `contents' for #<Chef::Util::FileEdit:0x00000002fbb218>
/opt/local/chef-repo/cookbooks/amimoto/recipes/nfs_client.rb:29:in `block in from_file'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.2/lib/chef/dsl/recipe.rb:136:in `instance_eval'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.2/lib/chef/dsl/recipe.rb:136:in `build_resource'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.2/lib/chef/dsl/recipe.rb:85:in `declare_resource'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.2/lib/chef/dsl/recipe.rb:41:in `method_missing'
/opt/local/chef-repo/cookbooks/amimoto/recipes/nfs_client.rb:26:in `from_file'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.2/lib/chef/mixin/from_file.rb:30:in `instance_eval'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.2/lib/chef/mixin/from_file.rb:30:in `from_file'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.2/lib/chef/cookbook_version.rb:234:in `load_recipe'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.2/lib/chef/run_context.rb:166:in `load_recipe'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.2/lib/chef/run_context.rb:135:in `block in include_recipe'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.2/lib/chef/run_context.rb:134:in `each'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.2/lib/chef/run_context.rb:134:in `include_recipe'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.2/lib/chef/dsl/include_recipe.rb:26:in `include_recipe'
/opt/local/chef-repo/cookbooks/amimoto/recipes/nfs_dispatcher.rb:12:in `from_file'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.2/lib/chef/mixin/from_file.rb:30:in `instance_eval'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.2/lib/chef/mixin/from_file.rb:30:in `from_file'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.2/lib/chef/cookbook_version.rb:234:in `load_recipe'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.2/lib/chef/run_context.rb:166:in `load_recipe'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.2/lib/chef/run_context/cookbook_compiler.rb:140:in `block in compile_recipes'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.2/lib/chef/run_context/cookbook_compiler.rb:138:in `each'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.2/lib/chef/run_context/cookbook_compiler.rb:138:in `compile_recipes'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.2/lib/chef/run_context/cookbook_compiler.rb:75:in `compile'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.2/lib/chef/run_context.rb:89:in `load'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.2/lib/chef/policy_builder/expand_node_object.rb:73:in `setup_run_context'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.2/lib/chef/client.rb:265:in `setup_run_context'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.2/lib/chef/client.rb:429:in `do_run'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.2/lib/chef/client.rb:213:in `block in run'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.2/lib/chef/client.rb:207:in `fork'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.2/lib/chef/client.rb:207:in `run'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.2/lib/chef/application.rb:236:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.2/lib/chef/application/solo.rb:226:in `block in run_application'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.2/lib/chef/application/solo.rb:218:in `loop'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.2/lib/chef/application/solo.rb:218:in `run_application'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.2/lib/chef/application.rb:55:in `run'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.2/bin/chef-solo:25:in `<top (required)>'
/usr/bin/chef-solo:23:in `load'
/usr/bin/chef-solo:23:in `<main>'
```

**Comment by marcy-terui** [comment]
このエラーが起きたのは以下での生成されるはずのファイルができていないからのようです。
（実際にサーバ上にありませんでした）
https://github.com/megumiteam/chef-amimoto/blob/master/recipes/nfs_client.rb#L21

**Comment by sawanoboly** [comment]
あちゃー
FileEditの変更で、そここけますね。

**Comment by marcy-terui** [comment]
あー、バージョン的なアレですか…

これですね。
https://github.com/chef/chef/commit/bd6079ddf7079c88d83f31335ec8bdfa5481b54b

リリース的には11.12か…

**Comment by marcy-terui** [comment]
直してみようかと思いましたが、これ環境作るのめんどいやつですねｗ

`kitchen-ec2`で`recipe[nfs_server]`実行済みを一台作って、
その情報もろもろ書いた`/opt/aws/cloud_formation.json`を作るダミーのrecipeを先に実行する感じでしょうか…

**Comment by sawanoboly** [comment]
元々privateメソッドを呼ぶような変なハックだし、コンパイル時に実行するも必要なかったのでruby_blockとパブリックメソッドに書き換え。

**Comment by sawanoboly** [comment]
@marcy-terui 

https://github.com/marcy-terui/jinkei-nagashino-vpc/blob/master/elb-amimoto-scale-nfs-with-rds.json

これで作った環境に修正後のレシピ流してNFSマウントまでOKでした。あとは @wokamoto さんが既存影響がないのを確認してmasterにマージするのを待ちます。

**Comment by marcy-terui** [comment]
おお、ありがとうございます！

できれば20日までに欲しかったりするのですが、AMIの更新が必要なんですかね？
（CookbookはAMI同梱なのか起動時に何処かから落とすスタイルなのか）
AMIの更新だと、Marketplaceのリリースプロセスはめんどいって聞いたので厳しいですよね…

**Comment by sawanoboly** [comment]
起動時に取ってくる仕様だから、レシピ更新だけ。

**Comment by marcy-terui** [comment]
そうなんですね！

無理にお願いするつもりはありませんが、
可能な範囲で早めに出してもらえると助かりますm(__)m

**Comment by sawanoboly** [comment]
マージされたし、もらったjsonそのまま長篠においていいかな？

@marcy-terui

**Comment by marcy-terui** [comment]
良いですよー

**Comment by sawanoboly** [comment]
動いた、ありがとう :smile: 

でもMPの制限でAmimotoが先日導入した、インスタンスIDを入力するコンファメーションでちょっと問題あり。
フロントのどれかのインスタンスIDを入力する運ゲーになってるので @wokamoto さんに報告しますね。

**Comment by marcy-terui** [comment]
おお、ちゃんと動きましたか！良かったです！
こちらこそありがとうございます！

あーそれ、僕も気になってましたｗ
あれ、マーケットプレイスの制限だったんですねー

**Comment by marcy-terui** [comment]
@wokamoto さん、ご対応ありがとうございました！
引き続きよろしくお願いします！
